stage:
    global:
        SKIP_HTML_MINIFICATION: true

    build:
        VERBOSE_COMMANDS: "-vv"
        SKIP_SCD: false
        SCD_STRATEGY: "standard"
        SCD_MATRIX:
            "Margifox/default":
                language:
                    - en_US
                    - en_AU
            "Magento/backend":
                language:
                    - en_AU
                    - en_US
    deploy:
        # Skip static asset compilation during deployment
        SKIP_SCD: true
        REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
        MYSQL_USE_SLAVE_CONNECTION: true
        REDIS_USE_SLAVE_CONNECTION: true
        CRON_CONSUMERS_RUNNER:
            cron_run: true
        SESSION_CONFIGURATION:
            _merge: true
            save: redis
        SEARCH_CONFIGURATION:
            engine: elasticsuite
            elasticsearch_server_hostname: 'elasticsearch.internal'
            elasticsearch_server_port: '9200'
            elasticsearch_index_prefix: 'margifox'
            elasticsearch_server_timeout: '15'
        ELASTICSUITE_CONFIGURATION:
            es_client:
                servers: 'elasticsearch.internal:9200'
                indices_alias: 'margifox'
            indices_settings:
                number_of_shards: 3
                number_of_replicas: 2
