<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()) :?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= (int)$_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= (int)$block->getRequest()->getParam('id') ?>" />
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>

        <!-- add description-->
        <?php if(!empty($_product->getShortDescription())) : ?>
            <div class="description">
                <span class="value">
                    <?= strip_tags($_product->getShortDescription()); ?>
                </span>
                    
                <span class="read-mode">
                    <?=__('Read mode')?>
                </span>
            </div>
        <?php endif;?>
        <!-- endadd description-->

        <?php if (!$block->hasOptions()) :?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else :?>
            <?php if ($block->getOptionsContainer() == 'container1') :?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($block->hasOptions() && $block->getOptionsContainer() == 'container2') :?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?= $block->getChildHtml('form_bottom') ?>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeHtml($_product->getId()) ?>]": {
            "priceBox": {
                "priceConfig":  <?= /* @noEscape */ $block->getJsonConfig() ?>
            }
        }
    }
</script>


<script>
    require(
        [
            'jquery'
        ],
        function($) 
        {
            jQuery(document).ready(function(){
  
                var element = $('.product-add-form').find('.description').find('span.value'),
                    fullDescription = element.text(),
                    partDescription = fullDescription.substring(0, 150);

                if (fullDescription === partDescription) {
                    element.text(fullDescription);
                    element.show();
                }else{
                    element.text(partDescription+'...');
                    $('.product-add-form').find('.description').find('.read-mode').addClass('show-more');
                }

                // Show more
                $(document).click(function(event) { 
                  $target = $(event.target);
                  if($target.closest('.description').length && $target.hasClass('read-mode')) {
                    if($target.hasClass('show-more')){
                        element.text(fullDescription);
                        $target.empty();
                        $target.removeClass('show-more');
                        $target.removeClass('show-less');
                        $target.addClass('show-less');
                        $target.text('Read less');
                        }else{
                            element.text(partDescription+'...');
                            $target.empty();
                            $target.removeClass('show-more');
                            $target.removeClass('show-less');
                            $target.addClass('show-more');
                            $target.text('Read more');
                        }
                  }        
                });
                // end Show more

            })
        }
    );
</script>
<style type="text/css">
    .read-mode {
        display: none;
    }
    .read-mode.show-more {
        display: inline-block;
    }
    .read-mode.show-less {
        display: inline-block;
    }
</style>
