<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$helper = $this->helper('Margifox\Customer\Helper\Data');
$customerName = $helper->getCustomerName();

 
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<?php if(!$helper->getLogin()) : ?>
	<div class="chat mobile">
		<a href="#"><?= __('Chat') ?></a>
	</div>

<?php endif;?>

<?php if(!$helper->getLogin()) : ?>
	<div class="authorization-link" data-label="<?= $block->escapeHtml(__('or')) ?>">
		<div class="top">
			
		    <a class="customer-login-link signin" <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
		        <?= __('Sign in / Join') ?>
		    </a>
		</div>
		
		<div class="bot">
		    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
		        <?= __('My Account') ?>
		    </a>
		</div>
	</div>
	<?php else : ?>
	<div class="authorization-link logged" data-label="<?= $block->escapeHtml(__('or')) ?>">
		<div class="top">
			<span class="name"><span><?= __('Hello, ').$customerName ;?></span></span>
		</div>
		
		<div class="bot">
		    <a href="<?=$this->getUrl('customer/account/');?>">
		        <?= __('View Account') ?>
		    </a>
		</div>
	</div>	
<?php endif;?>

