<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Details
 */
?>
<div class="block-requisition-management">
    <div class="requisition-content-container">
    <div class="requisition-tilte-box">
        <?= $block->getChildHtml('requisition.list.title') ?>
    </div>
    <?php if ($block->getParentBlock()->getItemErrorCount()) : ?>
        <div class="message error">
            <span>
                <?= (int) $block->getParentBlock()->getItemErrorCount() ?>
                <?= $block->escapeHtml(__('product(s) require your attention')) ?>
            </span>
        </div>
    <?php endif ?>

    <?php if ($block->getItemCount()) : ?>
        <div class="actions requisition-view-links">
            <?= $block->getChildHtml('requisition.list.print') ?>
        </div>
        <div class="requisition-info">
            <span class="counter qty">
                <?= (int)$block->getItemCount() ?>
                <?php if ($block->getItemCount() > 1) : ?>
                    <?= $block->escapeHtml(__('items')) ?>
                <?php else : ?>
                    <?= $block->escapeHtml(__('item')) ?>
                <?php endif ?>
            </span>
        </div>
    </div>
        <?= $block->getChildHtml('toolbar') ?>
    <?php endif ?>
</div>
