<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<?php
/** @var \Amasty\Blog\Block\Layout\AuthorInfo $block */
/** @var \Magento\Framework\Escaper $escaper */

$author = $block->getAuthorData();
?>

<?php if ($author): ?>
    <h2 class="amblog-article-title">
        <?= $escaper->escapeHtml(__('More from “%1”', $author->getName())); ?>
    </h2>
    <?php if ($author->getDescription()): ?>
        <div class="amblog-author-description">
            <?= $escaper->escapeHtml(nl2br($author->getDescription()), ['br']); ?>
        </div>
    <?php endif; ?>
    <h2 class="amblog-article-title">
        <?= $escaper->escapeHtml(__('Articles %1', $author->getName())); ?>
    </h2>
<?php endif; ?>
