<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
/** @var $block \Magento\Rma\Block\Email\Items */
?>
<table class="email-items rma-items" align="center" style="max-width: 600px;">
    <thead>
    <tr>
        <th style="width: 45%;padding-top: 24px;text-align: left;"><?= $block->escapeHtml(__('Product')) ?></th>
        <th style="padding-top: 24px;"><?= $block->escapeHtml(__('Condition')) ?></th>
        <th style="padding-top: 24px;"><?= $block->escapeHtml(__('Resolution')) ?></th>
        <th style="padding-top: 24px;"><?= $block->escapeHtml(__('Requested Qty')) ?></th>
        <th style="text-align: right;padding-top: 24px;"><?= $block->escapeHtml(__('Status')) ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getCollection() as $item) : ?>
    <tr>
        <td style="text-align: left;">
            <strong style="font-weight: 400;"><?= $block->escapeHtml($item->getProductName()) ?></strong>
            <?php if ($_options = $item->getOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                <dt style="color: #222222;margin-bottom: 0;"><?= $block->escapeHtml($_option['label']) ?></dt>
                <dd style="margin-bottom: 0;"><?= $block->escapeHtml($_option['value']) ?></dd>
                <?php endforeach; ?>
            </dl>
            <?php endif; ?>
        </td>
        <td><?= $block->escapeHtml($block->getOptionAttributeStringValue($item->getCondition())) ?></td>
        <td><?= $block->escapeHtml($block->getOptionAttributeStringValue($item->getResolution())) ?></td>
        <td><?= /* @noEscape */  $this->helper(Magento\Rma\Helper\Data::class)->parseQuantity($item->getQtyRequested(), $item) ?></td>
        <td style="text-align: right"><?= $block->escapeHtml($item->getStatusLabel()) ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
