<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Recommended items');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Recommended items');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $isWeightedRandom = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $isWeightedRandom = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('You may also like');
            $items = $block->getItemCollection();

            $showAddTo = false;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('You may also like');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
$catalogHelper = $this->helper('Margifox\Catalog\Helper\Data');
?>

<?php if ($exist): ?>

<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
     data-shuffle="<?= /* @noEscape */ $shuffle ?>"
     data-shuffle-weighted="<?= /* @noEscape */ $isWeightedRandom ?>">
    <?php else:?>
    <div class="block <?= $block->escapeHtmlAttr($class) ?>"
         data-mage-init='{"upsellProducts":{}}'
         data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
         data-shuffle="<?= /* @noEscape */ $shuffle ?>"
         data-shuffle-weighted="<?= /* @noEscape */ $isWeightedRandom ?>">
        <?php endif; ?>
        <?php else:?>
        <div class="block <?= $block->escapeHtmlAttr($class) ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading"
                        aria-level="2"><?= $block->escapeHtml($title) ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items" id="list-items">
                        <?php foreach ($items as $_item):?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'):?>
                                <?php if (!$_item->getRequiredOptions()):?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <li class="item product product-item" id="product-item_<?= /* @noEscape */ $_item->getId() ?>">
                            <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <div class="swatch-align">
                                        <?php
                                            if($_item->getTypeId() == 'configurable'){

                                                $swatchBlock = $catalogHelper->getConfigurableBlock();
                                                echo $swatchBlock->setProduct($_item)->toHtml();
                                            }
                                        ?>
                                    </div>
                                    <!-- add brand -->
                                    <?php
                                    $helper_customer = $this->helper('Margifox\Customer\Helper\Data');
                                    $_product = $helper_customer->getLoadProduct($_item->getId());
                                    $value_brand = $_product->getData('brand');
                                    $attribute_brand = $_product->getResource()->getAttribute('brand');
                                    $label_brand = $value_brand ? $attribute_brand->getSource()->getOptionText($value_brand) : '';
                                    ?>
                                    <div class="brand product-item-brand <?=$value_brand?>"><?=$label_brand?></div>
                                    <!-- end add -->

                                    <!-- <strong class="product-item-brand">= $block->escapeHtml($_item->getResource()->getAttribute('brand')->getFrontend()->getValue($_item)) ?></strong> -->
                                    <strong class="product name product-item-name"><a
                                                class="product-item-link"
                                                title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <?php if($helper_customer->getLogin()) : ?>
                                        <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                    <?php endif;?>

                                    <?php if ($templateType):?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($helper_customer->getLogin()) : ?>
                                        <div class="select-option-align">
                                            <div class="select-option">
                                                <?php if ($_item->isSaleable()) : ?>
                                                    <?php if ($_item->getTypeId() == 'configurable') : ?>
                                                        <?php if (!empty($catalogHelper->getConfigurableAttributes($_item))) : ?>
                                                            <?php foreach ($catalogHelper->getConfigurableAttributes($_item) as $key => $options) : ?>
                                                                <div class="attribute-options <?= $catalogHelper->getAttributeName($key) ?>">
                                                                    <select id="attribute-<?= $block->escapeHtml($key) ?>" data-attribute="<?= $block->escapeHtml($key) ?>"
                                                                            data-attribute-code="<?= $catalogHelper->getAttributeName($key) ?>">
                                                                        <?php if (!empty($options)) : ?>
                                                                            <?php $distinctOptions = $catalogHelper->getDistinctOptions($options) ?>
                                                                            <?php foreach ($distinctOptions as $option) : ?>
                                                                                <option value="<?= $option['value_index'] ?>">
                                                                                    <?= $block->escapeHtml($option['default_title']) ?>
                                                                                </option>
                                                                            <?php endforeach; ?>
                                                                        <?php endif; ?>
                                                                    </select>
                                                                </div>
                                                            <?php endforeach; ?>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable()
                                        && $type == 'related'):?>
                                        <?php if (!$_item->getRequiredOptions()):?>
                                            <div class="field choice related">
                                                <input
                                                    type="checkbox"
                                                    class="checkbox related"
                                                    id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                                    name="related_products[]"
                                                    value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                                <label class="label"
                                                       for="related-checkbox<?= $block->escapeHtmlAttr($_item->getId())
                                                        ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </label>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($showAddTo || $showCart):?>
                                        <?php // phpcs:disable ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart):?>
                                                <div class="actions-primary">
                                                <?php if ($_item->isSaleable()):?>
                                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)):?>
                                                        <button
                                                                class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                type="button"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else : ?>
                                                            <?php if ($helper_customer->getLogin()) : ?>
                                                            <?php
                                                            /** @var $viewModel PreparePostData */
                                                            $viewModel = $block->getViewModel();
                                                            $postArray = $viewModel->getPostData(
                                                                $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                                ['product' => $_item->getEntityId()]
                                                            );
                                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                            ?>
                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                                      action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?= /* @noEscape */
                                                                           (int)$_item->getEntityId() ?>">
                                                                    <input type="hidden"
                                                                           name="<?= /* @noEscape */
                                                                           ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                                           value="<?= /* @noEscape */
                                                                           $value ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>

                                                                    <div class="details-qty qty">
                                                                        <span class="minus"><i
                                                                                class="fas fa-minus"></i></span>
                                                                        <input type="number"
                                                                               name="qty"
                                                                               maxlength="12"
                                                                               value="<?php /* @escapeNotVerified */
                                                                               echo '1' ?>"
                                                                               data-validate="{'required-number':true,'validate-item-quantity':{'minAllowed':1,'maxAllowed':10000,'qtyIncrements':1}}"
                                                                               title="<?php /* @escapeNotVerified */
                                                                               echo __('Qty') ?>" class="input-text qty"/>
                                                                        <span class="plus"><i
                                                                                class="fas fa-plus"></i></span>
                                                                    </div>

                                                                    <button type="submit"
                                                                            title="<?= $block->escapeHtmlAttr(__('Add to cart')) ?>"
                                                                            class="action tocart primary">
                                                                        <span><?= $block->escapeHtml(__('Add to cart')) ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                                                   class="action primary"><?= $block->escapeHtml(__('View details')) ?></a>
                                                            <?php endif;?>

                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($helper_customer->getLogin()) : ?>

                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available">
                                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                </div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable">
                                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                </div>
                                                            <?php endif; ?>

                                                        <?php else : ?>

                                                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                                                   class="action primary"><?= $block->escapeHtml(__('View details')) ?></a>

                                                        <?php endif; ?>
                                                        
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php // phpcs:enable ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>

        <?php if ($type == 'related') : ?>
		<script>
            require([
                'jquery',
                'slick'
            ], function ($, slick) {
                jQuery(document).ready(function () {
                    $("#list-items").slick({
                        dots: true,
                          infinite: false,
                          speed: 300,
                          slidesToShow: 3,
                          slidesToScroll: 3,
                          responsive: [
                            {
                              breakpoint: 1025,
                              settings: {
                                slidesToShow: 2,
                                slidesToScroll: 2,
                                infinite: true,
                                dots: true
                              }
                            },
                            {
                              breakpoint: 992,
                              settings: {
                                slidesToShow: 3,
                                slidesToScroll: 3,
                                infinite: true,
                                dots: true
                              }
                            },
                            {
                              breakpoint: 600,
                              settings: {
                                slidesToShow: 2,
                                slidesToScroll: 2
                              }
                            },
                            {
                              breakpoint: 480,
                              settings: {
                                slidesToShow: 2,
                                slidesToScroll: 2
                              }
                            }
                            // You can unslick at a given breakpoint now by adding:
                            // settings: "unslick"
                            // instead of a settings object
                          ]
                    });
                    function alignHeight(selector) {
                        jQuery(selector).css('height', '');
                        var minHeight = 0;
                        jQuery(selector).each(function() {
                            if (minHeight < jQuery(this).outerHeight()) {
                                minHeight = jQuery(this).outerHeight();
                            }
                        });
                        if (minHeight > 0) {
                            jQuery(selector).css('height', minHeight);
                        }
                    }
                    setTimeout(function() {
                        alignHeight('.catalog-product-view .block.related .product-item-details .swatch-align');
                        alignHeight('.catalog-product-view .block.related .product-item-details .brand');
                        alignHeight('.catalog-product-view .block.related .product-item-details .product-item-name');
                        alignHeight('.catalog-product-view .block.related .product-item-details .price-box');
                        alignHeight('.catalog-product-view .block.related .product-item-details .select-option-align');
                        alignHeight('.catalog-product-view .block.related .product-item-details .product-item-actions');
                    }, 500);
                    jQuery(window).resize(function() {
                        setTimeout(function() {
                            alignHeight('.catalog-product-view .block.related .product-item-details .swatch-align');
                            alignHeight('.catalog-product-view .block.related .product-item-details .brand');
                            alignHeight('.catalog-product-view .block.related .product-item-details .product-item-name');
                            alignHeight('.catalog-product-view .block.related .product-item-details .price-box');
                            alignHeight('.catalog-product-view .block.related .product-item-details .select-option-align');
                            alignHeight('.catalog-product-view .block.related .product-item-details .product-item-actions');
                        }, 500);
                    });
                });
            });
        </script>
        <?php endif;?>

        <?php if (!$block->isRedirectToCartEnabled() && $_item):?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                    }
                }
            }
            </script>
        <?php endif;?>
        <?php endif;?>
