<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<?php
$helper_customer = $this->helper('Margifox\Customer\Helper\Data');
?>
<?php if($helper_customer->getLogin()) : ?>
    <div class="product alert <?= $block->getHtmlClass() ?>">
        <a href="<?= $block->escapeUrl($block->getSignupUrl()) ?>"
           title="<?= $block->escapeHtml(__($block->getSignupLabel())) ?>" class="action alert">
            <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
        </a>
    </div>
<?php endif; ?>
