<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <?php if($_code == 'shipping'): ?>
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= $block->escapeHtml('Shipping') ?></strong>
                <?php else : ?>
                    <?= $block->escapeHtml('Shipping') ?>
                <?php endif ?>
            </th>
        <?php elseif($_code == 'grand_total'): ?>
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> id="tot" scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= $block->escapeHtml('Total (Inc GST)') ?></strong>
                    <strong style="display: none;" class="or-title"><?= $block->escapeHtml('Grand total') ?></strong>
                <?php else : ?>
                    <?= $block->escapeHtml('Total (Inc GST)') ?>
                <?php endif ?>
            </th>
        <?php else: ?>
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                <?php else : ?>
                    <?= $block->escapeHtml($_total->getLabel()) ?>
                <?php endif ?>
            </th>
        <?php endif ?>
        <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()) : ?>
                <strong style="color:#222222;"><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
            <?php else : ?>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif; ?>
<?php endforeach?>
