mysql:
    type: mysql:10.3
    disk: 5120
    configuration:
        schemas:
            - main
        endpoints:
            mysql:
                default_schema: main
                privileges:
                    main: admin
            mbi:
                default_schema: main
                privileges:
                    main: ro

redis:
    type: redis:5.0

elasticsearch:
    type: elasticsearch:7.7
    disk: 1024
    configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic

rabbitmq:
    type: rabbitmq:3.8
    disk: 1024
