<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php /** @var \Amasty\Storelocator\Block\Location $block */ ?>
<?php

$productId = (int)$block->getRequest()->getParam('product');

if ($productId):
    $product = $block->getProductById($productId);
    ?>
    <h1><?= $block->escapeHtml($product->getName()); ?><?= $block->escapeHtml(__(' can be found at the following stores:&nbsp;')); ?></h1>
    <hr>
<?php endif; ?>
<div class="amlocator-main-container" style="<?= $block->escapeHtml($block->getMainBlockStyles()); ?>">
    <?php if ($block->getWidgetDescription()): ?>
        <div>
            <strong><?= $block->escapeHtml($block->getWidgetDescription()); ?></strong>
        </div>
    <?php endif; ?>
    <div class="amlocator-map-container" id="<?= $block->escapeHtml($block->getMapContainerId()); ?>">
        <div class="amlocator-map-top-box">
            <?php if ($block->getShowSearch()): ?>
            <div class="amlocator-search-container">
                <div class="amlocator-block -current amlocator-current-location">
                    <div class="amlocator-wrapper">
                        <input type="text" value="" class="address-fields"
                               name="address" placeholder="<?= $block->escapeHtml(__('Postcode or City')); ?>"
                               data-amlocator-js="address"
                               autocomplete="off">
                        <span class="amlocator-reset -hidden" data-amlocator-js="reset"></span>
                    </div>
                </div>
                <div class="amlocator-block -search amlocator-search-radius control">
                    <?php if ($block->getDistanceConfig() == 'choose'): ?>
                        <select class="amlocator-select -measurement" id="amlocator-measurement"
                                name="measurement" data-amlocator-js="measurment-select">
                            <option value="km"><?= $block->escapeHtml(__('km')); ?></option>
                            <option selected="selected" value="mi"><?= $block->escapeHtml(__('mi')); ?></option>
                        </select>
                    <?php else:?>
                        <input
                                type="hidden"
                                id="amlocator-measurement"
                                value="<?= $block->escapeHtml($block->getDistanceConfig()) ?>">
                    <?php endif ?>
                    <div class="amlocator-wrapper">
                        <?php if ($block->getRadiusType() == 'select' || empty($block->getRadiusType())): ?>
                            <select class="amlocator-select-custom" data-amlocator-js="radius-select" name="radius" >
                                <?php foreach ($block->getSearchRadius() as $range): ?>
                                    <option value="<?= is_numeric($range) ? (int)$range : ''; ?>">
                                        <?= is_numeric($range) ? (int)$range.''.$block->getDistanceLabel() : $range; ?>
                                    </option>
                                <?php endforeach;?>
                            </select>
                            <label class="amlocator-title label" id="range_radius" for="radius">
                                <?= $block->escapeHtml(__('Distance')); ?>
                            </label>
                        <?php else:?>
                            <div class="amlocator-range-slider" data-amlocator-js="range-slider">
                                <div class="amlocator-handle ui-slider-handle">
                                    <div class="amlocator-tooltip" tabindex="0">
                                        <span data-amlocator-js="radius-value"></span>
                                        <span data-amlocator-js="radius-measurment">
                                        <?= ($block->getDistanceConfig() != 'choose')
                                            ? $block->escapeHtml($block->getDistanceLabel())
                                            : '' ?>
                                    </span>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="radius"
                                   data-amlocator-js="radius-select"
                                   value="<?= (int)$block->getMaxRadiusValue(); ?>"
                                   min="<?= (int)$block->getMinRadiusValue(); ?>"
                                   max="<?= (int)$block->getMaxRadiusValue(); ?>"/>
                        <?php endif ?>
                    </div>
                </div>
                <?php if ($block->getShowLocations()): ?>
                <?php if ($attributes = $block->getAttributes()): ?>
                    <form class="attributes" action="#" data-amlocator-js="attributes-form">
                        <?php foreach ($attributes as $attribute): ?>
                            <div class="amlocator-attribute-wrapper">
                                <div class="amlocator-input-custom control">
                                    <select name="<?= (int)$attribute['attribute_id'];?>"
                                            class="amlocator-select-custom"
                                        <?php if ($attribute['frontend_input'] == 'multiselect'): ?>
                                            multiple="multiple"
                                            data-amlocator-js="multiple-select"
                                        <?php endif;?>>
                                        <?php if ($attribute['frontend_input'] != 'multiselect'):?>
                                            <option value="" selected><?= $block->escapeHtml(__('Select a brand')); ?></option>
                                        <?php endif?>
                                        <?php foreach ($attribute['options'] as $valueId => $option): ?>
                                            <option
                                                <?php if ($block->isOptionSelected(
                                                    $attribute,
                                                    $option
                                                )): ?>
                                                    selected
                                                <?php endif; ?>
                                                value="<?= (int)$option['value'] ?>">
                                                <?= $block->escapeHtml(
                                                    $option['label']
                                                ); ?>
                                            </option>
                                        <?php endforeach;?>
                                    </select>
                                    <label class="label" for="<?= (int)$attribute['attribute_id'];?>"><?= $block->escapeHtml($attribute['label']); ?></label>
                                </div>
                            </div>
                        <?php endforeach;?>
                    </form>
                    <div class="amlocator-actions">
                        <button class="action primary amlocator-button amlocator-filter-attribute"
                                title="<?= $block->escapeHtml(__('Search')) ?>">
                            <?= $block->escapeHtml(__('Search')); ?>
                        </button>
                    </div>
                <?php endif; ?>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            <div class="search-note">
                <?php
                    echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('text-above-map')
                    ->toHtml();
                ?>
            </div>
        </div>
        <div class="amlocator-map-bottom-box">
            <div class="amlocator-block -map">
                <div class="amlocator-map" id="<?= $block->escapeHtml($block->getMapId()); ?>"></div>
            </div>
            <div class="map-note">
                <p>Please Note: To ensure you are receving our authentic products we highly recommend that you ONLY order from authorised resellers. <a href="#" title="">Learn more</a></p>
            </div>
        </div>
    </div>
</div>

<script>
require([
    'jquery',
    'Amasty_Storelocator/js/main',
    'Amasty_Storelocator/js/cluster',
    'domReady!',
    'mage/loader',
    'https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $block->escapeHtml(
        $block->configProvider->getApiKey()
    ); ?>'
], function ($) {
    var mapId =  "<?= '#' . $block->escapeHtml($block->getMapId()); ?>",
        $body = $('body'),
        isLoaderAjaxInitiated = !!$.data($body.get(0), 'mage-loader'),
        isLoaderInitiated = isLoaderAjaxInitiated,
        initFunction,
        tryToInit = function () {
            if (isLoaderInitiated && isLoaderAjaxInitiated) {
                initFunction();

                return true;
            }

            return false;
        };

    initFunction = function () {
        $(mapId).amLocator({
            amMediaUrl :"<?= $block->escapeHtml($block->getAmStoreMediaUrl()); ?>",
            mapZoom: <?= $block->escapeHtml($block->getMapZoom()); ?>,
            productId: "<?= (int)$block->getProductId() ?>",
            categoryId: "<?= (int)$block->getCategoryId() ?>",
            automaticLocate: "<?= (bool)$block->getAutomaticLocate(); ?>",
            enableClustering: "<?= (bool)$block->getClustering(); ?>",
            enableSuggestionClickSearch: "<?= (bool)$block->getSuggestionClickSearch(); ?>",
            enableCountingDistance: "<?= (bool)$block->getCountingDistance(); ?>",
            distanceConfig: "<?= $block->escapeHtml($block->getDistanceConfig()); ?>",
            useGeoConfig: "<?= (bool)$block->getGeoUse()?>",
            allowedCountries: <?= /* @noEscape */ $block->getAllowedCountries(); ?>,
            ajaxCallUrl: "<?= $block->escapeHtml(
                $block->getUrl('amlocator/index/ajax') . $block->getQueryString()
            ); ?>",
            useBrowserLocation: "<?= (bool)$block->getUseBrowserLocation()?>",
            jsonLocations: <?= /* @noEscape */ $block->getJsonLocations() ?>,
            imageLocations: "<?= $block->escapeHtml($block->getViewFileUrl('Amasty_Storelocator::images/')); ?>",
            mapId : "<?= $block->escapeHtml($block->getMapId()); ?>",
            mapContainerId: "<?= $block->escapeHtml($block->getMapContainerId()); ?>",
            showSearch: <?= (int)$block->getShowSearch(); ?>,
            <?php if ($block->getRadiusType() == 'range'):?>
                isRadiusSlider: <?= $block->escapeHtml($block->getRadiusType()) == 'range'?>,
                maxRadiusValue: <?= (int)$block->getMaxRadiusValue(); ?>,
                minRadiusValue: <?= (int)$block->getMinRadiusValue(); ?>,
                measurementRadius: "<?= ($block->getDistanceConfig() != 'choose') ?
                    $block->escapeHtml($block->getDistanceLabel()) : ''?>"
            <?php endif;?>
        });
    };

    tryToInit();
    $body.on('loadercreate', function () {
        isLoaderInitiated = true;
        tryToInit();
    }).on('loaderajaxcreate', function () {
        isLoaderAjaxInitiated = true;
        tryToInit();
    });
})
</script>
