<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="box-multipleskus">
    <div class="fields additional deletable-item-title">
        <div class="field sku">
            <label for="multiple_skus" class="label">
                <span><?= $block->escapeHtml(__('Enter multiple SKUs')) ?></span>
            </label>
        </div>
    </div>
    <div class="fields additional deletable-item" data-role="new-block">
        <div class="field sku ui-front">    
            <div class="control custom-control">
                <textarea
                    name="multiple_skus"
                    data-role="multiple-skus"
                    id="multiple_skus"
                    title="Enter multiple SKUs"
                    data-id="multiple_skus"
                    aria-required="false"
                    rows="2"
                    placeholder=" "
                    class="input-text"
                    ></textarea>
                <label class="label" for="multiple_skus"><?= $block->escapeHtml(__('Enter multiple SKUs')) ?></label>
            </div>
            <div class="note">
                <p><?= $block->escapeHtml(__('Use commas or paragraph to separate SKUs.')) ?></p>
            </div>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="secondary">
            <button type="button"
                    title="<?= $block->escapeHtmlAttr(__('Add to List')) ?>"
                    class="action move-to-single-skus"
                    data-mage-init='{"quickOrderMultipleSkus":{
                    "urlSku":"<?= /* @noEscape */ $block->getUrl('quickorder/ajax/search') ?>"
                    }}'>
                <span><?= $block->escapeHtml(__('Add to List')) ?></span>
            </button>
        </div>
    </div>
</div>