<div class="brand-content-wrapper" data-bind="scope: 'section'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
    	"*": {
        	"Magento_Ui/js/core/app": {
            	"components": {
                	"section": {
                    	"component": "Margifox_BrandRewardUi/js/section"
                	}
            	}
        	}
    	}
    }
</script>
