<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate


/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();

$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$childProd = current($_item->getChildrenItems());
if($childProd = current($_item->getChildrenItems()))
{
        $productImage = $_imagehelper->init($childProd->getProduct(), 'category_page_list', array('height' => '86' , 'width'=> '86') )->getUrl();
}
else{
    $helper = $this->helper('Margifox\Email\Helper\Data');
    $productImage = $helper->getEmailProductImage($_item->getProductId()); 
}

?>

<tr>
    <td style="padding-top:0;" class="item-info" <?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <img style="max-width:80px !important;width:86px !important;height:auto !important;padding-right: 12px;padding-bottom:0px;float:left;padding-top: 18px;" src="<?php print_r($productImage);?>" title="<?= $block->escapeHtml($_item->getName()) ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>" />
    </td>
    <td style="padding-top: 0;">
        <p class="product-name" style="padding-top:18px;width: 100%;"><?= $block->escapeHtml($_item->getName()) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options" style="display: grid;margin-top:-20px;line-height:20px;">
            <?php foreach ($block->getItemOptions() as $option) : ?>
                <?php if($option['label'] == 'Created at'){
                    continue;
                }  
                ?>
                <p class="title-option" style="float:left;color:#222;font-weight:700;font-family:'Arial';"><?= $block->escapeHtml($option['label']) ?></p>
                <p class="value-option" style="text-transform: uppercase;float:left;color:#222;font-family:'Arial';"><?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?></p>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-subtotal">
        <?= '$'.$block->escapeHtml($_item->getPrice()) ?>
    </td>
    <td class="item-qty" style="padding-left: 50px;"><?= (float) $_item->getQtyOrdered() ?></td>
    <td class="item-total">
       <?= /* @noEscape */ $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
    <tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                    <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
