<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
$_product = $block->getProduct();
$helper = $this->helper('Margifox\Customer\Helper\Data');
$helper_catalog = $this->helper('Margifox\Catalog\Helper\Data');
$qty = '';
?>

<?php if($helper->getLogin()) : ?>
  
  <?php if(!$_product->isSaleable()) : ?>
    <span class="out-stock"><?=__('Out of stock');?></span>
  <?php else : ?>

    <?php if($_product->getTypeId() == 'simple') : ?>
      <?php 
        $qty = $helper_catalog->getQtyProduct($_product);
        $message = __('%1 items in stock.',$qty);
      ?>
        <span class="salable qty"><?=$message;?></span>
    <?php endif;?>

    <?php if($_product->getTypeId() == 'configurable') : ?>
      <span class="salable qty configuration"></span> 
    <?php endif;?>

  <?php endif; ?>

  <?php if ($block->isWishListAllowed()) : ?>
      <a href="#"
         class="action towishlist"
         data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
         data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wishlist')) ?></span></a>
  <?php endif; ?>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
