<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Loyalty and Promo Allocations')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Loyalty Points Earned')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <?= $block->getChildHtml('order_loyalty_points_earned_listing') ?>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Loyalty Points Redeemed')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <?= $block->getChildHtml('order_loyalty_points_redeemed_listing') ?>
            </div>
        </div>
    </div>
</section>
